services:
  db:
    image: postgres:14-alpine
    volumes:
    - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: test

volumes:
  db_data:
