#!/bin/bash

# Set correct `DATABASE_URL` for `STAGE=local`.
#
# Usage:
#   . prisma/url $POSTGRES_DB
#
# Args:
#   POSTGRES_DB - name of PostgreSQL database, e.g. "test", default is "start".

export STAGE=local

# As this script is sourced to external shell, which may be not `bash`, e.g. on CI,
# `[[` may be not found, so we use `test` instead.
if test "${CI-false}" = true
then
    :
    # Using CI PostgreSQL service.
    # Both `POSTGRES_HOST` and `POSTGRES_DB` are set in CI config.
else
    POSTGRES_HOST=localhost
    POSTGRES_DB=${1-start}
fi

export DATABASE_URL="postgresql://postgres@$POSTGRES_HOST:5432/$POSTGRES_DB?schema=public"
